import { fileURLToPath } from "node:url";
import { PGlite } from "@electric-sql/pglite";
import { drizzle } from "drizzle-orm/pglite";
import { migrate } from "drizzle-orm/pglite/migrator";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import * as schema from "../schema";

const migrationsFolder = fileURLToPath(new URL("../../drizzle", import.meta.url));

let client: PGlite;

beforeAll(async () => {
  client = new PGlite();
  await migrate(drizzle({ client, schema }), { migrationsFolder });
});

beforeEach(async () => {
  await client.exec("RESET ROLE; TRUNCATE registrations;");
});

afterAll(async () => {
  await client.close();
});

// The reference is generated by the app (`$defaultFn`), so raw SQL supplies its own.
const insertRow = `
  INSERT INTO registrations (reference, race, first_name, last_name, email, mobile, birthdate,
    sex, shirt_size, emergency_contact_name, emergency_contact_mobile, consent_at, amount_centavos)
  VALUES ('RR-' || substr(md5(random()::text), 1, 8), '5k', 'Test', 'Runner',
    'runner@example.test', '+639170000000', '1990-01-01', 'male', 'M', 'Test Contact',
    '+639170000001', now(), 80000)
  RETURNING id`;

/** Run `sql` as `role` and return the Postgres error code, or null if it succeeded. */
async function errorCodeAs(role: string, sql: string): Promise<string | null> {
  try {
    await client.exec(`SET ROLE ${role}; ${sql}`);
    return null;
  } catch (error) {
    return (error as { code?: string }).code ?? "unknown";
  } finally {
    await client.exec("RESET ROLE");
  }
}

describe("migrations", () => {
  it("apply cleanly to an empty database and are not re-applied", async () => {
    const { rows } = await client.query<{ n: number }>(
      "SELECT count(*)::int AS n FROM drizzle.__drizzle_migrations",
    );
    expect(rows[0]?.n).toBe(2);
    await expect(migrate(drizzle({ client, schema }), { migrationsFolder })).resolves.not.toThrow();
  });
});

describe("rr_app", () => {
  it("is a group role that cannot log in", async () => {
    const { rows } = await client.query<{ rolcanlogin: boolean; rolsuper: boolean }>(
      "SELECT rolcanlogin, rolsuper FROM pg_roles WHERE rolname = 'rr_app'",
    );
    expect(rows).toEqual([{ rolcanlogin: false, rolsuper: false }]);
  });

  it("can read, insert and update registrations", async () => {
    expect(await errorCodeAs("rr_app", insertRow)).toBeNull();
    expect(await errorCodeAs("rr_app", "SELECT * FROM registrations")).toBeNull();
    expect(
      await errorCodeAs("rr_app", "UPDATE registrations SET status = 'cancelled' RETURNING *"),
    ).toBeNull();
  });

  it.each([
    ["DELETE", "DELETE FROM registrations"],
    ["TRUNCATE", "TRUNCATE registrations"],
    ["DROP TABLE", "DROP TABLE registrations"],
    ["ALTER TABLE", "ALTER TABLE registrations ADD COLUMN x text"],
    ["CREATE INDEX", "CREATE INDEX x_idx ON registrations (email)"],
    ["CREATE TABLE", "CREATE TABLE public.x (id int)"],
    ["CREATE SCHEMA", "CREATE SCHEMA x"],
    ["ALTER TYPE", "ALTER TYPE registration_status ADD VALUE 'refunded'"],
    ["read migration history", "SELECT * FROM drizzle.__drizzle_migrations"],
  ])("is denied %s", async (_label, sql) => {
    await client.exec(insertRow);
    expect(await errorCodeAs("rr_app", sql)).toBe("42501");
  });

  it("holds exactly SELECT, INSERT and UPDATE on registrations, and cannot pass them on", async () => {
    // Postgres only warns on a GRANT without grant option, so check the effect instead.
    expect(await errorCodeAs("rr_app", "GRANT SELECT ON registrations TO PUBLIC")).toBeNull();
    const privileges = [
      "SELECT",
      "INSERT",
      "UPDATE",
      "DELETE",
      "TRUNCATE",
      "REFERENCES",
      "TRIGGER",
    ];
    const held: Record<string, boolean> = {};
    for (const p of privileges) {
      const { rows } = await client.query<{ ok: boolean }>(
        `SELECT has_table_privilege('rr_app', 'registrations', '${p}') AS ok`,
      );
      held[p] = rows[0]?.ok ?? false;
    }
    expect(held).toEqual({
      SELECT: true,
      INSERT: true,
      UPDATE: true,
      DELETE: false,
      TRUNCATE: false,
      REFERENCES: false,
      TRIGGER: false,
    });
    const { rows } = await client.query<{ ok: boolean }>(
      "SELECT has_table_privilege('public', 'registrations', 'SELECT') AS ok",
    );
    expect(rows[0]?.ok).toBe(false);
  });

  it("passes the same rights to a login role created as in the runbook", async () => {
    await client.exec(
      "DO $$ BEGIN CREATE ROLE rr_app_login LOGIN IN ROLE rr_app; " +
        "EXCEPTION WHEN duplicate_object THEN NULL; END $$;",
    );
    expect(await errorCodeAs("rr_app_login", insertRow)).toBeNull();
    expect(await errorCodeAs("rr_app_login", "SELECT * FROM registrations")).toBeNull();
    expect(await errorCodeAs("rr_app_login", "DELETE FROM registrations")).toBe("42501");
    expect(await errorCodeAs("rr_app_login", "DROP TABLE registrations")).toBe("42501");
  });
});
